In [1]:
# coding a single neuron
inputs = [1,2,3]
weights = [0.2, 0.8, -0.5]
bias = 2

outputs = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] +bias)
print(outputs)

2.3


In [1]:
#coding a layer
inputs = [1,2,3,2.5]
weights = [[0.2, 0.8, -0.5, 1],[0.5, -0.91, 0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]
weights1 = weights[0] #list of weights associated with 1st neuron
weights2 = weights[1] #2nd neuron
weights3 = weights[2] #3rd neuron

biases = [2,3,0.5]
bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
    #Neuron 1:
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,
    # Neuron 2:
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,
    # Neuron 3:
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3,
]
print(outputs)

[4.8, 1.21, 2.385]


In [2]:
#using for loops for easier and better coding
inputs = [1, 2, 3, 2.5]

##LIST OF WEIGHTS
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

##LIST OF BIASES
biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
 # Zeroed output of given neuron
 neuron_output = 0
 # For each input and weight to the neuron
 for n_input, weight in zip(inputs, neuron_weights):
 # Multiply this input by associated weight
 # and add to the neuron's output variable
   neuron_output += n_input*weight ## W31*X1 + W32*X2 + W33*X3 + W34*X4
   # Add bias
 neuron_output += neuron_bias ## ## W31*X1 + W32*X2 + W33*X3 + W34*X4 + B3
 # Put neuron's result to the layer's output list
 layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


In [ ]:
# using numpy to code a neuron
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
outputs = np.dot(weights, inputs) + bias # np.dot(weights, inputs) = np.dot(inputs, weights) --> only for single neuron, not for layer
#bcz in layers weight is a matrix , here both are vectors
print(outputs)

4.8


In [5]:
# using numpy to code a layer
# in plain python, we wrote this as a list of lists.
# With Numpy, this will be a 2D array, which we'll call a matrix.
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8,-0.5,1],[0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]
# A dot product of a matrix and vector results in a list of dot products.
# The np.dot() method treats the matrix as a list of vectors and 
# performs a dot product of each of those vectors with the other vector.
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


In [7]:
# multiple sets of input i.e. batch of inputs
inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],[0.5, -0.91,0.26, -0.5],[-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]
# we cant transpose list in python, so we have to convert the weights matrix into an array first.
outputs = np.dot(inputs, np.array(weights).T + biases)
print(outputs)

[[19.8   23.71   6.135]
 [22.9   19.19   3.7  ]
 [ 6.81   9.151  1.376]]


In [8]:
# coding multiple neural network layers and stacking them together
# 2 layers
inputs = [[1,2,3,2.5],[2.,5.,-1.,2], [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2,3,0.5]
weights2 = [[0.1, -0.14, 0.5], [-0.5, 0.12, -0.33], [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]
# convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)
#calculate output of first layer
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array
# output of second layer
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
