In [ ]:
import numpy as np
A=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
A = np.array(A)
print("np.sum(A)  sum of all elements of array: ")
print(np.sum(A))
print("np.sum(A, axis = None)  sum of all elements of array: ")
print(np.sum(A, axis = None))
print("np.sum(A, axis = 0)  : adds the rows") #returns 1D array
print(np.sum(A, axis = 0)) # 1X3
print("np.sum(A, axis = 1)  : adds the columns") # returns 1D array
print(np.sum(A, axis = 1))  #1X3
# use keepdims to keep dim of resulting array same as the given array
print(np.sum(A, axis = 0, keepdims = True)) #1X3
print(np.sum(A, axis = 1, keepdims = True)) #3X1

np.sum(A)  sum of all elements of array: 
45
np.sum(A, axis = None)  sum of all elements of array: 
45
np.sum(A, axis = 0)  : adds the rows
[12 15 18]
np.sum(A, axis = 1)  : adds the columns
[ 6 15 24]
[[12 15 18]]
[[ 6]
 [15]
 [24]]


In [ ]:
# two matrix can only be added/substracted if they have same rows and cols no.
# but python uses broadcasting where if one dim are equal, and if other one is 1 or doesnot exist for one, then python stretches the col/row to match the col/row of other
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[1,1,1]]
A = np.array(A)
B = np.array(B)
print(A+B)
C = [[2],[2],[2]]
C = np.array(C)
print(A+C)
print(B+C)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
